### ISSUE TITLE
Provide tooltip / description for each metric

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#1066]
# Feature request

## Description

As a user, I want to understand each metric right away. To do so, I want to read tooltips about the functionality of the visualized metric.

Feature: Provide tooltip / description for each metric - both primary and secondary. These descriptions have to be added to the cc.json file from the importer. The fields are optional to stay backwards compatible

## Acceptance criteria

- Change the cc.json in a backwards compatible way to accept new meta data. This meta data contains descriptions for the used metrics
- The descriptions are defined in each importer. The importer adds them to the cc.json
- Additionally, read-more links (documentation links) can be specified optionally.
- ~~The descriptions explain what a high or low value indicates for a specific metric.~~ (Will be done in #3232)
- The visualizer understands the new cc.json file and adds the new information to the metrics as tooltips
- Metric Names in the Frontend have a tooltip with the short description including the read-more link (Legend, Selectboxes of metrics, primary/secondary metrics in sidebar when clicking on a building, etc.).
- Full test coverage for the new / changed code

## Development notes (optional Task Breakdown)

Next important TODO(s):
- [x] Display the new attribute descriptors in the legend #3162
- [ ] Display the new attribute descriptors in the metric choosers #3273 ~~#3163~~ 
- [ ] Display the new attribute descriptors in the sidebar. #3273 #3239 
    - [x] Show Descriptor Title, Description, Hint High Value and Hint Low Value maybe in a tooltip
    - [ ] Link to external documentation (Attribute Descriptor Link). #3273 

We can skip the Custom Views for now. Keep in mind that we want the current approach with metricTitles.ts (or similarily named) to provide descriptions for cc.json files without attribute descriptors as fallback.

It is recommended to open separate PRs to update the importers (maybe just one at a time), to update the cc.json structure for the new information and to update the visualizer. That way it's easy to review and to quickly land the PRs.

> "title" field added in #3158 

- [x] Model #3091 #3158
- [x] Filter/EdgeFilter #3091
- [x] Filter/MergeFilter #3091
- [x] Filter/StructureModifier #3091
- [x] Import/CodeMaatImporter #3091
- [x] Import/CSVImporter #3091
- [x] Import/GitLogParser #3091
- [x] Import/MetricGardenerImporter #3091
- [x] Import/SonarImporter #3149
- [x] Import/SourceCodeParser #3166 
- [x] Import/SVNLogParser #3176 
- [x] Import/TokeiImporter #3176 
- [x] Parser/RawTextParser (descriptors do not apply here)

**Comment by ce-bo** [comment]
Showing/Adding hints for what a low/high value indicates for a specific metric will be done in a follow up #3232
