### ISSUE TITLE
Improve custom configs

### ISSUE THREAD

**Issue by BridgeAR** [MaibornWolff/codecharta#2489]
# Feature request

## Description

As a user, I want custom configs to be easily understandable and easy to use so that I do not have to invest a lot of time using them.

## Acceptance criteria
Please address the tasks (when in makes sense) in separate PRs to deliver value to the customer in small interations.

### Minimum set before releasing the feature as stable:
- [x] Remove notification when removing entries (just remove the entry by collapsing the list)
- [x] "AI" entries should not be kept in the local storage. They are recalculated as soon as the map is loaded anyway. As discussed [here](https://github.com/MaibornWolff/codecharta/issues/2435), this will resolve #2435 and #2436.
- [x] Do not close Custom Config menu after deleting a config. 
- [x] Do not show non-matching entries by default! Only list matching entries for the loaded maps. All others should be in a separate category.  
- [x] Rename everything related to custom configs/map to "Custom view"
- [x ] Separate applicable and not-applicable entries.
- [x] Add a "Show not-applicable entries" button below the list of applicable views and hide those by default.
- [x] Add a subtitle in the Custom Views Modal to explain in one sentence for what the User can use it (e.g. Store your current Settings/Configuration, Download and Import them.). Add a link to the docs for more information.
- [x] Partially applicable entries (only a single map is loaded and there's a custom view for that map in multiple mode in combination with another map) count as applicable. #3090
- [x] Partially applicable entries should be clickable but greyed out. While hovering over those, show what is missing to apply that custom view (e.g. map X is not loaded;map X is loaded in standard mode, but config is created for delta mode). On click, the config should still be applied, although it is greyed out. #3090
- [x] Add icons/names/descriptions of `metrics` (area: rloc, height: foo, color: bar) and `mode` (single,multiple,delta) below the custom view name. (#3119)
- [x] "Somehow" show the used colors (at least if they deviate from the default [green, yellow, red]) in the view  (#3119)
- [x] Rename "multiple" to "standard" mode in list view (e.g. "Custom View(s) in mutliple mode for ...."). (#3119)

### Tasks to release the feature as a stable one:
------
- [x] Mark custom configs as stable (should be shown also when experimental mode is disabled)
- [x] Add a How To article in our documentation. Describe how to use it, how to Download/Import/Share custom configs. Describe how and why it is replacing the download button.
- [x] Show a deprecation warning in the changelog that the download button is going to be removed soon. Link to the How To article.
- [x] Show deprecation warning in the "Export File" modal when clicking on the download button that the download functionality is going to be removed soon and that the Custom Views feature can be used instead. Link to the How To article to provide more information.
- [x] Add a nice „NEW“ Feature Sticker in the ribbon bar.
- [x] Grey out the download button, but it should still be clickable. 
- [x] Create a GitHub issue to remove the download button (do not do that now) or to open the Custom  Views Modal on Click instead. 
------

**Comment by ce-bo** [comment]
Duplicate: #2462

**Comment by BridgeAR** [comment]
@ce-bo the mentioned issue has no specific description how to improve the situation.

**Comment by BridgeAR** [comment]
Related #1548

**Comment by ce-bo** [comment]
@BridgeAR What was meant by `Highlight matching entries for the currently loaded mode (single, multiple, diff)`?

**Comment by BridgeAR** [comment]
@ce-bo I meant something like adding a small indicator below the entry that outlines the mode (next to e.g., the used metrics).

Something along the lines of (it should be styled appropriately and this is just a random box I found right now): 
![image](https://user-images.githubusercontent.com/8822573/148259166-56848371-c126-4832-b17f-eb347c5145b1.png)

**Comment by Christian-Eberhard** [comment]
Here are the design suggestions we worked on in the workshop.

![SavedViewsVersions.png](https://images.zenhubusercontent.com/6076b0525fa0ae9470963a22/aec6fea0-41a7-4200-aaf5-e5b59e3ee874)

**Comment by BridgeAR** [comment]
This is currently blocked by a migration of the following components:

- Download button
- Upload Button
- List view
- Sublist view

**Comment by ce-bo** [comment]
> This is currently blocked by a migration of the following components:
> 
> * Download button
> * Upload Button
> * List view
> * Sublist view

@shaman-apprentice @Hall-Ma Are the components already migrated?

**Comment by Hall-Ma** [comment]
@ce-bo It's done.

**Comment by ce-bo** [comment]
To deliver the CustomViews Feature as a stable one faster, we should prioritize the open tasks. I think not all are really needed to work with it productively. So before you start, please let us first discuss it.

**Comment by ce-bo** [comment]
@Hall-Ma I changed the priority of the remaining sub tasks.
Let's continue with "Tasks to release the feature as a stable one:" :-)
