### ISSUE TITLE
Create CodaCharta Docker container

### ISSUE THREAD

**Issue by jannikr** [MaibornWolff/codecharta#2946]
# Feature request

Within a Docker container, both the frontend and the backend are to be loaded with all the necessary dependencies to run the project on different platforms. Furthermore, it would be practical to start SonarQube server with the necessary properties to cover as many programming languages as possible.

## Description

As a user, I want to quickly import and parse source code on different platforms so that I can upload it on the CodeCharta website without any dependency issues.

## Acceptance criteria
- Create docker container
- Add task to install npm, java, ...
- Add task to install CodeCharta Analysis and Visualization
- Add task for SonarQube Server with specific properties like default user and password.
- Add Documentation for a basic workflow in order to parse source code and upload it on CodeCharta

## Task Breakdown

- [x] Fix Visualisation container
   - [x] CC-Analysis does not get installed?
   - [x] Tag "latest" does not get correctly applied (https://user-images.githubusercontent.com/108457762/192304553-dd74b80e-de7b-4860-9f84-e742696c02d6.png)
- [x] Create new analysis container
   - [x] Add Git
   - [x] Add Tokei
   - [x] Add Sonar (Via docker-compose)
   - [x] Add Code Maat
   - [x] Add Metric Gardener
- [x] Write cool docker-compose for the new containers
- [x] Adjust build/release process
- [ ] Update or write new docs if necessary

**Comment by MW-Friedrich** [comment]
@ce-bo SourceMonitor seems to be only available on Windows. (https://www.derpaul.net/SourceMonitor) 
While Windows emulation on Linux is possible with wine and Proton, it would be quite a huge undertaking. Is it okay if we don't include it in the container?

**Comment by ce-bo** [comment]
@MW-Friedrich that‘s fine. The most important thing is to have SonarQube running. By that, we already can analyse a lot of programming languages. Additionally, the User will be able to import CSV files from SourceMonitor by our importers.
