### ISSUE TITLE
Improve Custom Configs #2

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#3155]
# Feature request

<Please note by far the quickest way to get a new feature is to file a Pull Request.>
<We will consider your request but it may be closed,>
<if it's something we're not actively planning to work on>
<or it does not match our visison of this software.>

## Description

As a user, I want custom configs to be easily understandable and easy to use so that I do not have to invest a lot of time using them.

## Acceptance criteria
Please address the tasks (when in makes sense) in separate PRs to deliver value to the customer in small interations.

### Tasks

- [ ] Allow editing a custom view name by double clicking on the name. This makes the name editable. Safe the new name on unfocus.
- [ ] Show a checkbox next to the entries while hovering over the entry. If at least a single checkbox is activated, show a action button with which the user may delete or download the corresponding entries.
- [ ] Also show a checkbox "somewhere" next to the action button (no matter if anything is yet clicked upon or not) that allows to (de-)select all visible entries.
- [ ] Add a search bar that allows to search for custom configs by name, metric, mode, groupname or similar parts. Use e.g., "🔎 Custom views..." as default text that is hidden on focus. Provide a "X" button to clear the input of the search field. (It should be a simple search field that filters the Custom Views in the list on keystroke)
