### ISSUE TITLE
Improve Custom Configs #3

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#3156]
# Feature request

<Please note by far the quickest way to get a new feature is to file a Pull Request.>
<We will consider your request but it may be closed,>
<if it's something we're not actively planning to work on>
<or it does not match our visison of this software.>

## Description

As a user, I want custom configs to be easily understandable and easy to use so that I do not have to invest a lot of time using them.

## Acceptance criteria
Please address the tasks (when in makes sense) in separate PRs to deliver value to the customer in small interations.

### Tasks
- [ ] Group entries automatically on insertion.
- [ ] Extend Action Button logic for groups (download, delete selected ones).
- [ ] Allow to change the custom view order of groups and individual entries with drag and drop.
- [ ] Auto delete empty groups (this happens by deleting individual entries or by moving the last entry out of a group).
- [ ] Allow to merge two groups by dragging an existing group on top of another one (and show a hovering effect for the hovered group).
------
- [ ] TBD: Improve the import functionality and use a new input window for this. Concrete behavior requires further definition.
- [ ] Resolve https://github.com/MaibornWolff/codecharta/issues/940 as cleanup after removing the download button
------
