### ISSUE TITLE
Tech: Bump Minimum Node.js Version from 16 to 18

### ISSUE THREAD

**Issue by MW-Friedrich** [MaibornWolff/codecharta#3168]
# Update Minimum Required Node.js Version

CodeCharta should update the required Node.js Version from 16 to 18 by no later than [2023-09-11](https://nodejs.org/en/blog/announcements/nodejs16-eol/), since v16 has its end of life by then.

## Task Breakdown

- [x] Update package.json (codecharta)
- [x] Update package.json (visualization)
- [x] Update regular test pipeline
- [x] Update release pipeline
- [x] Update Docker container(s)
- [x] Update Documentation
    - [x] gh-pages
    - [x] readme files

**Comment by fritschldwg** [comment]
Reasons for the upgrade:
- #3318: This issue gets solved by using npm v10 (which comes with node v18) in analysis containers
- #3294: Upgrading Angular to v17 will require node v18 (https://angular.io/guide/versions)

**Comment by ce-bo** [comment]
Let's check how to separate the versioning before we merge the node update.

**Comment by shaman-apprentice** [comment]
After the upgrade to Node 18 I can do the Angular 17 upgrade. My first experiences with Angular 17 are much better than with Angular 16 :) I strongly suggest to incrementally adapt to new [template syntax](https://angular.dev/guide/templates/control-flow).
