### ISSUE TITLE
RawTextParser fails for multiple inputs

### ISSUE THREAD

**Issue by fritschldwg** [MaibornWolff/codecharta#3406]
# RawTextParser fails for multiple inputs
This issue consolidates various problems associated with the RawTextParser. The following are specific problems identified:

- [x] (1) The 'metrics', 'exclude', and 'file-extensions' parameters are not handled correctly (handled in [#3415](https://github.com/MaibornWolff/codecharta/pull/3415))
- [x] (2) The default value for the 'max-indentation-level' parameter is set incorrectly (handled in [#3419](https://github.com/MaibornWolff/codecharta/pull/3419))
- [x] (3) RawTextParser crashes when provided with various 'max-indentation-level' values
- [ ] (4) RawTextParser hangs when using default parameters [#3422](https://github.com/MaibornWolff/codecharta/pull/3422))
- [ ] (5) RawTextParser exhibits diverging behaviors when configured using flags compared to configuration via the KotlinInquirer
- [ ] (6) RawTextParser crashes when given invalid metric [#3424](https://github.com/MaibornWolff/codecharta/pull/3424))

## Expected Behavior (1)

<GIVEN>

WHEN
- Executing 
   - ccsh rawtextparser → leave specified parameters empty
   - OR ccsh → select rawtextparser → leave specified parameters empty
   - OR ccsh -i → select rawtextparser → leave specified parameters empty
   - OR ccsh rawtextparser "path-to-folder-or-file" --metrics= --file-extensions=   
   --exclude=

THEN
- All files and metrics are included for parsing

## Actual Behavior (1)
- No files are included for parsing
- No metrics are included for parsing

## Screenshots (1)
<img width="652" alt="RawTextParser not including files and metrics" src="https://github.com/MaibornWolff/codecharta/assets/149768491/fce15475-8018-47e6-9f0b-b56752768f06">

## Steps to Reproduce the Problem (1)
1. Configure rawtextparser interactively
2. Leave specified parameters empty

## Expected Behavior (2)

<GIVEN>

WHEN
- Executing 
   - ccsh rawtextparser -h 
   - ccsh rawtextparser "path-to-folder-or-file"

THEN
- Max-indentation-level is set to 10 (as specified in the help command)

## Actual Behavior (2)
- Max-indentation-level is set to 6

## Steps to Reproduce the Problem (2)
1. Run: ccsh rawtextparser "path-to-folder-or-file"

## Expected Behavior (3)

<GIVEN>

WHEN
- Executing 
   - ccsh rawtextparser "path-to-analysis" --max-indentation-level=7 
   - OR ccsh rawtextparser "path-to-analysis" --max-indentation-level=8

THEN
- The files in the analysis folder are parsed accordingly

## Actual Behavior (3)
- RawTextParser crashes with the exceptions specified in the screenshot

## Screenshots (3)
<img width="782" alt="RawTextParser crashes on max-indentation-level=7" src="https://github.com/MaibornWolff/codecharta/assets/149768491/70670fe8-51d5-494f-a1af-d24805dc4ab5">

<img width="754" alt="RawTextParser crashes on max-indentation-level=8" src="https://github.com/MaibornWolff/codecharta/assets/149768491/2b6842ae-3df8-447e-b9bc-31abd75b2507">

## Steps to Reproduce the Problem (3)
1. Run: ccsh rawtextparser "path-to-analysis" --max-indentation-level=7 
    OR : ccsh rawtextparser "path-to-analysis" --max-indentation-level=8

## Expected Behavior (4)

<GIVEN>

WHEN
- Executing 
   - ccsh rawtextparser
   - specifying output file
   - selecting default values for other parameters

THEN
- The files in the specified folder are parsed accordingly

## Actual Behavior (4)
- RawTextParser hangs after parsing files

## Screenshots (4)
<img width="800" alt="Parser hanging" src="https://github.com/MaibornWolff/codecharta/assets/149768491/98330024-fda6-4ca3-a079-296359859d74">

## Steps to Reproduce the Problem (4)
1. Run: ccsh rawtextparser
3. Specify output file
4. Select default values for other parameters

## Expected Behavior (5)

<GIVEN>

WHEN
- Executing 
   - ccsh rawtextparser "path-to-analysis" --tab-width=0 --max-indentation-level=10
   - ccsh -i → select rawtextparser → specify values as in the previous command interactively

THEN
- Both commands produce the same output

## Actual Behavior (5)
- The first command crashes
- The second command hangs

## Steps to Reproduce the Problem (5)
1. Run: ccsh rawtextparser "path-to-analysis" --tab-width=0 --max-indentation-level=10
2. Execute: ccsh -i → select rawtextparser → specify values as in the previous command 

## Expected Behavior (6)

<GIVEN>

WHEN
- Executing executing the RawTextParser and giving it an invalid metric to calculate

THEN
- It ignores this metric

## Actual Behavior (6)
- The RawTextParser crashes with an UnsupportedOperationException

## Steps to Reproduce the Problem (6)
1. Execute the RawTextParser interactively or directly
2. Pass it a metric other than "IndentationLevel"

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes
- CodeCharta Version: version "1.120.0"
- OS: Windows
- Browser: -

**Comment by ce-bo** [comment]
Thank you @fritschldwg!

Please create individual pull requests per issue.
