### ISSUE TITLE
EPIC: Navigation and Camera issues

### ISSUE THREAD

**Issue by ChristianHuehn** [MaibornWolff/codecharta#3661]
# Epic
This will be more of an epic than single issues.

## Issues
The camera and the navigation is pretty clunky right now. To improve this we have a couple of issues to work on. Which will help users to navigate and move around the map.
After working on these we can add more to this.

- [x] https://github.com/MaibornWolff/codecharta/issues/1539
- [x] https://github.com/MaibornWolff/codecharta/issues/3147
- [x] https://github.com/MaibornWolff/codecharta/issues/753
- [x] https://github.com/MaibornWolff/codecharta/issues/3478
- [x] https://github.com/MaibornWolff/codecharta/issues/851
- [x] https://github.com/MaibornWolff/codecharta/issues/3194
- [x] https://github.com/MaibornWolff/codecharta/issues/3682
