### ISSUE TITLE
EPIC: GH-Pages Changes

### ISSUE THREAD

**Issue by Nereboss** [MaibornWolff/codecharta#3719]
# Epic
This will be more of an epic than single issues.

## Issues
Since cleaning up the documentation in GH-pages, there were some topics that occurred on how the GH-pages should be further improved. This will be a list of them:

- [ ] Write a script that automatically copies the content of READMEs of each parser to their page in the GH-pages
- [ ] Remove the ADRs from the GH-pages and find a more fitting place for them
- [ ] Rethink/rework the How-To Articles section in the GH-pages. 
- [ ] Rethink the landing page of the GH-pages to be more inviting

**Comment by ChristianHuehn** [comment]
https://github.com/MaibornWolff/codecharta/issues/3801
