### ISSUE TITLE
Epic: Correct validation for future versions of the cc.json API

### ISSUE THREAD

**Issue by NearW** [MaibornWolff/codecharta#938]
# Bug

This is an epic and lists bullet points on how we achieve this. Each bullet point is an own small issue. Please work on that in chronological order.

- [x] ~~Validate file before exporting with the schema validator #946~~
- [x] Create a API.md that documents what changes between each cc.json API version #939
- [ ] Use different interfaces for internal and external types. CodeMapNode and ExportCodeMapNode should be different, since the ExportCodeMapNode does not include properties like `isFlattened` #940
- [x] ~~Create a migration-filter that takes any valid cc.json and migrates it to the current API version. Also upgrade the API version to 1.2 since we changed the AttributeTypes. #884~~
- [x] Use typescript-json-schema to generate the new schemes with a script in order to always validate correctly, when the schema changes and we therefore have a new API version #860

**Comment by BridgeAR** [comment]
Closing since all of these have a corresponding issue and just one of these is not yet addressed / should still be addressed.
